# Generated by Django 4.0.6 on 2022-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_document_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Word', models.CharField(max_length=100)),
                ('Score', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
    ]
