# Generated by Django 4.0.6 on 2022-12-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dictionary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='Score',
        ),
        migrations.RemoveField(
            model_name='dictionary',
            name='Word',
        ),
    ]
